# Generated by Django 3.0.5 on 2020-04-25 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maid', models.BooleanField(null=True)),
                ('internet', models.BooleanField(null=True)),
                ('parking', models.BooleanField(null=True)),
                ('security', models.BooleanField(null=True)),
                ('cctv', models.BooleanField(null=True)),
                ('address', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('dormitory_dormitory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dormitory')),
            ],
        ),
        migrations.CreateModel(
            name='user_Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=50)),
                ('user_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceC', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('romm_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Room')),
                ('user_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('romm_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Room')),
            ],
        ),
        migrations.AddField(
            model_name='dormitory',
            name='user_owner_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_Owner'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('room_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Room')),
                ('user_customer_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_customer')),
            ],
        ),
    ]
