# Generated by Django 3.0.5 on 2020-04-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_user_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
