# Generated by Django 3.0.5 on 2020-04-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dormitory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='NameDM',
            field=models.CharField(default='', max_length=255),
        ),
    ]
