# Generated by Django 3.0.5 on 2020-04-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='dormitory_dormitory_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Air', 'Air'), ('Fan', 'Fan')], default='found', max_length=255),
        ),
        migrations.DeleteModel(
            name='user_more',
        ),
    ]
