# Generated by Django 3.0.5 on 2020-04-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200428_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
        migrations.AddField(
            model_name='room',
            name='Room_Price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.CharField(choices=[('BIG', 'BIG'), ('MEDIUM', 'MEDIUM'), ('SMALL', 'SMALL')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('empty', 'empty'), ('full', 'full')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='type_room',
            field=models.CharField(choices=[('Air', 'Air'), ('Fan', 'Fan')], default='', max_length=50),
        ),
    ]
