# Generated by Django 3.0.5 on 2020-04-28 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200428_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dormitory_dormitory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Dormitory'),
        ),
    ]
