# Generated by Django 3.0.5 on 2020-04-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_room_dormitory_dormitory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='name',
        ),
        migrations.AddField(
            model_name='furniture',
            name='List_furniture',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='romm_room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Room'),
        ),
    ]
