# Generated by Django 3.0.5 on 2020-04-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_room_room_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dormitory',
            old_name='user_owner_user_id',
            new_name='user_Owner_user_id',
        ),
    ]
