# Generated by Django 3.0.5 on 2020-04-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200428_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dormitory',
            old_name='type',
            new_name='typeP',
        ),
    ]
