# Generated by Django 3.0.5 on 2020-04-28 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_auto_20200428_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_owner',
            name='address',
        ),
        migrations.AlterField(
            model_name='user_customer',
            name='romm_room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Room'),
        ),
        migrations.AlterField(
            model_name='user_customer',
            name='user_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
