# Generated by Django 3.0.5 on 2020-04-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200428_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_customer',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='user_customer',
            name='priceC',
        ),
        migrations.RemoveField(
            model_name='user_customer',
            name='start_time',
        ),
    ]
