# Generated by Django 3.0.5 on 2020-04-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200428_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Owner_Customer',
        ),
    ]
