# Generated by Django 3.0.5 on 2020-04-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_delete_user_owner_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='create_date',
        ),
    ]
