# Generated by Django 3.0.5 on 2020-04-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200428_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='text',
        ),
    ]
