# Generated by Django 3.0.5 on 2020-04-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_user_customer_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_customer',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Dormitory'),
        ),
    ]
