# Generated by Django 3.0.5 on 2020-04-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200429_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Room_picture2',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='Room_picture3',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='Room_picture4',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='Room_picture5',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='Room_picture',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
