# Generated by Django 3.0.5 on 2020-04-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200429_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Room_picture',
            new_name='Room_picture1',
        ),
    ]
