# Generated by Django 3.0.5 on 2020-04-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_room_send_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Send_request',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
