# Generated by Django 3.0.5 on 2020-04-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200429_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Send_request',
        ),
        migrations.AddField(
            model_name='user_customer',
            name='Send_request',
            field=models.BooleanField(default=False),
        ),
    ]
