# Generated by Django 3.2.3 on 2021-05-15 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0033_auto_20210514_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='typebook',
            name='booktp',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='typebook',
            name='size',
            field=models.CharField(choices=[('cartoon', 'cartoon'), ('fiction', 'fiction'), ('documentary', 'documentary'), ('fairy', 'fairy')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='Contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='Detail',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='user_owner_user_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('typebook_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.typebook')),
            ],
        ),
        migrations.CreateModel(
            name='user_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Send_request', models.BooleanField(default=False)),
                ('history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('romm_room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.typebook')),
                ('user_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
