# Generated by Django 3.2.3 on 2021-05-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210515_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typebook',
            old_name='size',
            new_name='typee',
        ),
        migrations.RemoveField(
            model_name='typebook',
            name='booktp',
        ),
        migrations.AddField(
            model_name='book',
            name='Price',
            field=models.CharField(default='', max_length=255),
        ),
    ]
