# Generated by Django 3.2.3 on 2021-05-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210515_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_owner_user_customer',
            old_name='typebook_id',
            new_name='room_id',
        ),
        migrations.AddField(
            model_name='user_customer',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user_customer',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
