# Generated by Django 3.2.3 on 2021-05-15 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_room_id_user_owner_user_customer_typebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_Owner_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user_owner'),
        ),
    ]
