# Generated by Django 3.0.3 on 2021-05-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_book_user_owner_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='typebook',
            name='select',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='', max_length=50),
        ),
    ]
