# Generated by Django 3.2.3 on 2021-05-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_typebook_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typebook',
            name='select',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='', max_length=50),
        ),
    ]
